In [1]:
# setup
import pandas as pd
from arcgis import GIS
from arcgis.features import FeatureLayer

In [2]:
# setup connection to GIS Portal, this can be and empty GIS() function with a public service
gis = GIS()

In [3]:
# get feature service as a Spatially Enabled Dataframe
service_url = "https://maps.trpa.org/server/rest/services/LTinfo_Climate_Resilience_Dashboard/MapServer/128"
feature_layer = FeatureLayer(service_url)
query_result = feature_layer.query()
# Convert the query result to a Spatially Enabled Dataframe, this brings the SHAPE with it and can be saved back as a spatial file
sdfParcels = query_result.sdf

In [4]:
sdfParcels

,OBJECTID,variable_code,variable_name,value,Geography,year_sample,dataset,sample_level,Category
0,1,B03002_012E,Total population: Hispanic or Latino,11423,Basin,2020,acs/acs5,block group,Race and Ethnicity
1,2,B03002_012E,Total population: Hispanic or Latino,12151,Basin,2021,acs/acs5,block group,Race and Ethnicity
2,3,DP1_0093C,Total population: Hispanic or Latino,12027,Basin,2020,dec/dp,tract,Race and Ethnicity
3,4,P004003,Total population: Hispanic or Latino,12203,Basin,2010,dec/sf1,tract,Race and Ethnicity
4,5,P008010,Total population: Hispanic or Latino,11035,Basin,2000,dec/sf1,tract,Race and Ethnicity
...,...,...,...,...,...,...,...,...,...
454,455,B25003B_001E,Total: Black Or African American Alone Househo...,92,South Lake,2021,acs/acs5,tract,Tenure by Race
455,456,B25003E_001E,Total: Native Hawaiian And Other Pacific Islan...,8,South Lake,2021,acs/acs5,tract,Tenure by Race
456,457,B25003F_001E,Total: Some Other Race Alone Householder,680,South Lake,2021,acs/acs5,tract,Tenure by Race
457,458,B25003G_001E,Total: Two Or More Races Householder,1006,South Lake,2021,acs/acs5,tract,Tenure by Race
458,459,B25003A_001E,Total: White Alone Householder,13102,South Lake,2021,acs/acs5,tract,Tenure by Race

In [46]:
# here's an example of a function to get web service data as a regular Pandas dataframe
def get_fs_data(service_url):
    feature_layer = FeatureLayer(service_url)
    query_result = feature_layer.query()
    # Convert the query result to a list of dictionaries
    feature_list = query_result.features
    # Create a pandas DataFrame from the list of dictionaries
    all_data = pd.DataFrame([feature.attributes for feature in feature_list])
    # return data frame
    return all_data

In [47]:
feature_layer = FeatureLayer(service_url)
query_result = feature_layer.query()
feature_list = query_result.features
all_data = pd.DataFrame([feature.attributes for feature in feature_list])
all_data

,OBJECTID,STOP_ID,STOP_NAME,LATITUDE,LONGITUDE,NETWORK,GlobalID,created_user,created_date,last_edited_user,last_edited_date
0,1,12428,7-11/Regional Park,39.326248,-120.177104,TART,{B8A5B0A9-9283-4BEA-80F2-CB411AB9DF75},None,None,None,None
1,2,12430,Donner Pass Rd at Donner Memorial State Park,39.32481989,-120.2327303,TART,{12CCE163-5541-4990-99E5-ABCBF6F26FBF},None,None,None,None
2,3,13593,"Ritz Carlton, Highlands Court",39.267333,-120.12784,TART,{EF7721AE-8953-4C77-9F50-2F2FF2CC3673},None,None,None,None
3,4,2120,Country Club Dr at Incline Way,39.24092945,-119.94032,TART,{FAE6196B-FF73-415F-9DE6-EBBF343B5B65},None,None,None,None
4,5,2121,Country Club Dr at Mill Creek,39.24247914,-119.938123,TART,{EDE4C128-052A-4FEB-A0DD-AB72A23CE51B},None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
351,355,9854,Donner Pass Rd at Highway Rd,39.32557709,-120.2222231,TART,{6CA00A77-BB16-4E55-BBD4-3B5CA713C564},None,None,None,None
352,356,9855,Donner Pass Rd Cold Stream Rd,39.32291464,-120.2275942,TART,{FAE71BE9-B377-46FA-93E1-F356D3660855},None,None,None,None
353,357,9856,Donner Pass Rd at Moraine Rd (Sticks Market),39.32895356,-120.2512487,TART,{0207253D-9B1E-4483-A585-3BB9DCE72D83},None,None,None,None
354,358,9858,Donner Pass Rd at Donner Lake Village Resort,39.32480287,-120.2866209,TART,{5751D5A2-8797-437E-AC1F-19075857FFEB},None,None,None,None
355,359,9869,Hampton Inn,39.317133,-120.152433,TART,{77418408-37CE-44E6-85A0-CDA79E3618ED},None,None,None,None